name: Build dev version artifacts for window
on:
  push:
    branches:
      - feat-github-action-win

jobs:

  win-build:
    runs-on: windows-latest
    steps:
      #- name: Checkout repository
      #  uses: actions/checkout@v2
      - name: See environment
        run: where.exe cmake ninja 7z clang gcc vcpkg
      - name: See versions
        run: |
          cmake --version
          ninja --version
          clang --version
          gcc --version
      - name: See Path
        run: $env:path -split ';'
      - name: Make dirs
        run: |
          mkdir bin
          mkdir archives
          mkdir bin/mingw64
          mkdir bin/Qt6.4.0-gcc12-shared
      - name: Download mingw64
        run: curl -o archives/gcc12.7z https://github.com/niXman/mingw-builds-binaries/releases/download/12.2.0-rt_v10-rev0/x86_64-12.2.0-release-posix-seh-rt_v10-rev0.7z
      - name : Extract mingw
        run: 7z x -o.\bin ./archives/gcc12.7z
      - name: Tree
        run: tree .

        #https://github.com/niXman/mingw-builds-binaries/releases/download/12.2.0-rt_v10-rev0/x86_64-12.2.0-release-posix-seh-rt_v10-rev0.7z