name: Build dev version artifacts for window
on:
  push:
    branches:
      - feat-github-action-win

jobs:

  win-build:
    runs-on: windows-latest
    steps:
      #- name: Checkout repository
      #  uses: actions/checkout@v2
      - name: See environment
        run: where.exe cmake ninja 7z clang gcc vcpkg
      #- name: See versions
      #  run: |
      #    cmake --version
      #    ninja --version
      #    clang --version
      #    gcc --version
      - name: See Path
        run: $env:path -split ';'
      - name: Make dirs
        run: |
          mkdir bin
          mkdir bin/mingw64
          mkdir bin/Qt6.4.0-gcc12-shared
          mkdir build
          mkdir 3rdParty
      - name: Download mingw64 and extract
        run: | 
          cmd
          curl -JL -o bin/gcc12.7z "https://github.com/niXman/mingw-builds-binaries/releases/download/12.2.0-rt_v10-rev0/x86_64-12.2.0-release-posix-seh-rt_v10-rev0.7z"
          7z x -obin bin/gcc12.7z
          exit
        # gcc installation dir: bin/mingw64
        # gcc.exe: bin/mingw64/bin/gcc.exe
        # g++.exe: bin/mingw64/bin/g++.exe
      - name: Build and install zlib
        run: |
          $basedir=(pwd).path
          cd 3rdParty
          git clone https://github.com/madler/zlib.git
          cd zlib
          git checkout v1.2.13
          cd $basedir
          mkdir bin/build-zlib
          cmake -G Ninja -S 3rdParty/zlib -B bin/build-zlib -DCMAKE_C_COMPILER="bin/mingw64/bin/gcc.exe" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$basedir/bin/mingw64"
          cmake --build bin/build-zlib --parallel
          cmake --install bin/build-zlib
          
      - name: Upload gcc
        uses: actions/upload-artifact@v3
        with:
          name: gcc12-with-zlib
          path: bin/mingw64
          if-no-files-found: error    
            
      - name: Download Qt6.4.0-gcc12-shared and extract
        run: |
          cmd
          curl -JL -o bin/Qt6.4.0-gcc12-shared.7z "https://github.com/SlopeCraft/VisualCraft-binaries/releases/download/win-binaries/Qt6.4.0-gcc12-shared.7z"
          7z x -obin bin/Qt6.4.0-gcc12-shared.7z
          exit
        # Qt installation dir: bin/Qt6.4.0-gcc12-shared
      #- name: Build and install libzip
      #  run: |
      #    cmd
      #    cd 3rdParty
      #    git clone https://github.com/nih-at/libzip.git
      #    cd libzip
      #    git checkout v1.9.2
      #    cd ..

      #    cd ..