name: Build dev version artifacts
on: 
  pull_request:
  push:
    branches:
      - update-sc-ui

jobs:

  macos-check-libpng:
    runs-on: macos-latest
    steps:
      - name: brew update
        run: brew update
      - name: install libpng
        run: brew install libpng
      - name: find png.h
        run: find . -name png.h
