name: Build dev version artifacts
on: 
  pull_request:
  push:
    branches:
      - update-sc-ui

jobs:

  macos-check-libpng:
    runs-on: macos-latest
    steps:
      - name: find png.h
        run: find /Library -name png.h -print
      - name: cat png.h
        run: cat /Library/Frameworks/Mono.framework/Headers/png.h
      - name: cat png.h with grep
        run: cat /Library/Frameworks/Mono.framework/Headers/png.h | grep png_write_row

      - name: Upload png.h and png_conf.h
        uses: actions/upload-artifact@v3
        with: 
          name: libpng headers on macos from brew
          path: /Library/Frameworks/Mono.framework/Headers/png*
          if-no-files-found: error 