name: Build dev version artifacts
on: 
  pull_request:
  push:
    branches:
      - update-sc-ui

jobs:

  macos-check-libpng:
    runs-on: macos-latest
    steps:
      - name: brew update
        run: | 
          brew update-reset
          brew update
      - name: install libpng
        run: brew install libpng
      - name: find png.h
        run: find /System/Volumes/Data/usr/local -name png.h -print
      - name: cat png.h
        run: cat /System/Volumes/Data/usr/local/Cellar/libpng/1.6.39/include/libpng16/png.h
      - name: cat png.h with grep
        run: cat /System/Volumes/Data/usr/local/Cellar/libpng/1.6.39/include/libpng16/png.h | grep png_write_row

      - name: Upload png.h and png_conf.h
        uses: actions/upload-artifact@v3
        with: 
          name: libpng headers on macos from brew
          path: /System/Volumes/Data/usr/local/Cellar/libpng/*
          if-no-files-found: error 