name: Build dev version artifacts
on: 
  pull_request:
  push:
    branches:
      - opencl-in-github-action

jobs:
  
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install cmake, ninja
        run: sudo apt install cmake ninja-build

      - name: Install libzip, libpng, Eigen3
        run: sudo apt install libzip-dev zipcmp ziptool zipmerge libpng-dev libeigen3-dev

      - name: Install qt6
        run: sudo apt install libqt6widgets6 libqt6gui6 libqt6network6 libqt6concurrent6 qt6-base-dev qt6-tools-dev-tools qt6-tools-dev qt6-l10n-tools
      
      - name: Install additional qt-related packages
        run: sudo apt install x11-utils libxcb-xinerama0 libxv1 libgl-dev
        # Without these libs, cmake cannot find Qt6::Gui. But if you install nvidia-cuda-toolkit, they will be installed automatically
      - name: Install OpenCL
        run: sudo apt install nvidia-cuda-toolkit
        #nvidia-cuda-dev ocl-icd-libopencl1 ocl-icd-opencl-dev ocl-icd-dev opencl-c-headers opencl-clhpp-headers
      - name: List all packages
        run: apt list --installed
      - name: find cl.hpp
        run: sudo find / -name cl.hpp

